import { FloodStage } from './simulationStages';
import type { StagePayload } from './simulationTypes';

const DEFAULT_MAP = { markers: [], polygons: [], routes: [], heatmap: [] };

export const FLOOD_SCENARIO_DATA: Record<FloodStage, StagePayload> = {
  [FloodStage.NORMAL]: {
    stageEnum: FloodStage.NORMAL,
    name: 'Normal',
    description: 'Systems nominal. No active threats detected.',
    durationMs: 0,
    weather: { temperature: 28, rainfall: 0, humidity: 60, windSpeed: 10, condition: 'Clear' },
    threat: { riskLevel: 'LOW', riskScore: 10, confidence: 99 },
    ai: { title: 'System Nominal', summary: 'All city sectors operating normally.', recommendation: 'Maintain standard monitoring.', reasoning: ['Weather patterns stable', 'No active incidents reported'], confidence: 99 },
    incidentFeed: [],
    resources: { rescueTeams: { deployed: 0, available: 15 }, ambulances: { deployed: 2, available: 40 }, fireUnits: { deployed: 1, available: 30 }, police: { deployed: 10, available: 100 } },
    shelters: { available: 10, occupied: 0, capacity: 5000 },
    roads: { closed: 0, congested: 5, safe: 120 },
    population: { affected: 0, evacuated: 0, atRisk: 0 },
    map: DEFAULT_MAP
  },
  [FloodStage.HEAVY_RAIN]: {
    stageEnum: FloodStage.HEAVY_RAIN,
    name: 'Heavy Rain',
    description: 'Intense rainfall starts across the city.',
    durationMs: 0,
    weather: { temperature: 24, rainfall: 45, humidity: 85, windSpeed: 25, condition: 'Heavy Rain' },
    threat: { riskLevel: 'MODERATE', riskScore: 35, confidence: 80 },
    ai: { title: 'Precipitation Alert', summary: 'Unexpected heavy rainfall detected.', recommendation: 'Alert low-lying areas.', reasoning: ['Rainfall exceeds 40mm/hr', 'Drainage systems nearing capacity'], confidence: 85 },
    incidentFeed: [{ id: 'inc-1', title: 'Severe Waterlogging', description: 'Water pooling on major arterial roads.', severity: 'low', timestampOffset: 5, location: { lat: 19.076, lng: 72.877 } }],
    resources: { rescueTeams: { deployed: 2, available: 13 }, ambulances: { deployed: 5, available: 37 }, fireUnits: { deployed: 3, available: 28 }, police: { deployed: 15, available: 95 } },
    shelters: { available: 10, occupied: 0, capacity: 5000 },
    roads: { closed: 0, congested: 15, safe: 110 },
    population: { affected: 500, evacuated: 0, atRisk: 10000 },
    map: DEFAULT_MAP
  },
  [FloodStage.CITIZEN_REPORTS]: {
    stageEnum: FloodStage.CITIZEN_REPORTS,
    name: 'Citizen Reports',
    description: 'Citizens begin reporting localized flooding.',
    durationMs: 0,
    weather: { temperature: 23, rainfall: 65, humidity: 90, windSpeed: 35, condition: 'Torrential Rain' },
    threat: { riskLevel: 'HIGH', riskScore: 60, confidence: 88 },
    ai: { title: 'Flood Risk Elevated', summary: 'Multiple reports of water entering residential areas.', recommendation: 'Prepare evacuation protocols.', reasoning: ['Citizen reports clustering in Sector 4', 'Rainfall continuing unabated'], confidence: 90 },
    incidentFeed: [{ id: 'inc-2', title: 'Basement Flooding', description: 'Residential complex basements submerged.', severity: 'medium', timestampOffset: 2, location: { lat: 19.080, lng: 72.880 } }],
    resources: { rescueTeams: { deployed: 5, available: 10 }, ambulances: { deployed: 10, available: 32 }, fireUnits: { deployed: 8, available: 23 }, police: { deployed: 30, available: 80 } },
    shelters: { available: 10, occupied: 0, capacity: 5000 },
    roads: { closed: 2, congested: 25, safe: 98 },
    population: { affected: 2500, evacuated: 50, atRisk: 25000 },
    map: DEFAULT_MAP
  },
  [FloodStage.WATER_LEVEL_RISING]: {
    stageEnum: FloodStage.WATER_LEVEL_RISING,
    name: 'Water Level Rising',
    description: 'River sensors indicate critical water levels.',
    durationMs: 0,
    weather: { temperature: 23, rainfall: 80, humidity: 95, windSpeed: 45, condition: 'Storm' },
    threat: { riskLevel: 'HIGH', riskScore: 75, confidence: 92 },
    ai: { title: 'Critical Water Levels', summary: 'Mithi River approaching danger mark.', recommendation: 'Dispatch early warning units.', reasoning: ['Sensor R-4 exceeded 3.5m', 'Tide expected to rise in 2 hours'], confidence: 94 },
    incidentFeed: [{ id: 'inc-3', title: 'River Overflow Risk', description: 'Water breaching banks near Kurla.', severity: 'high', timestampOffset: 0, location: { lat: 19.072, lng: 72.883 } }],
    resources: { rescueTeams: { deployed: 8, available: 7 }, ambulances: { deployed: 15, available: 27 }, fireUnits: { deployed: 12, available: 19 }, police: { deployed: 45, available: 65 } },
    shelters: { available: 10, occupied: 200, capacity: 5000 },
    roads: { closed: 5, congested: 40, safe: 80 },
    population: { affected: 8000, evacuated: 500, atRisk: 45000 },
    map: DEFAULT_MAP
  },
  [FloodStage.FLOOD_WARNING]: {
    stageEnum: FloodStage.FLOOD_WARNING,
    name: 'Flood Warning',
    description: 'Official flood warning broadcasted citywide.',
    durationMs: 0,
    weather: { temperature: 22, rainfall: 90, humidity: 98, windSpeed: 50, condition: 'Severe Storm' },
    threat: { riskLevel: 'CRITICAL', riskScore: 90, confidence: 98 },
    ai: { title: 'Imminent Flash Flood', summary: 'Flash flood inevitable in low-lying zones.', recommendation: 'Execute mandatory evacuation.', reasoning: ['River breached danger mark', 'Rainfall peaking'], confidence: 99 },
    incidentFeed: [{ id: 'inc-4', title: 'Evacuation Ordered', description: 'Mandatory evacuation for Wards L & N.', severity: 'critical', timestampOffset: 1, location: { lat: 19.075, lng: 72.890 } }],
    resources: { rescueTeams: { deployed: 12, available: 3 }, ambulances: { deployed: 25, available: 17 }, fireUnits: { deployed: 20, available: 11 }, police: { deployed: 70, available: 40 } },
    shelters: { available: 12, occupied: 1200, capacity: 6000 },
    roads: { closed: 12, congested: 50, safe: 63 },
    population: { affected: 20000, evacuated: 3500, atRisk: 80000 },
    map: DEFAULT_MAP
  },
  [FloodStage.ROAD_CLOSURE]: {
    stageEnum: FloodStage.ROAD_CLOSURE,
    name: 'Road Closure',
    description: 'Major arterial roads are impassable.',
    durationMs: 0,
    weather: { temperature: 22, rainfall: 85, humidity: 98, windSpeed: 45, condition: 'Severe Storm' },
    threat: { riskLevel: 'CRITICAL', riskScore: 95, confidence: 99 },
    ai: { title: 'Logistics Compromised', summary: 'Multiple routes blocked by flood water.', recommendation: 'Reroute emergency vehicles via elevated highways.', reasoning: ['Expressway submerged at 3 points', 'Traffic gridlock detected'], confidence: 97 },
    incidentFeed: [{ id: 'inc-5', title: 'Expressway Blocked', description: 'Water level reached 4 feet on highway.', severity: 'critical', timestampOffset: 2, location: { lat: 19.060, lng: 72.850 } }],
    resources: { rescueTeams: { deployed: 14, available: 1 }, ambulances: { deployed: 35, available: 7 }, fireUnits: { deployed: 25, available: 6 }, police: { deployed: 85, available: 25 } },
    shelters: { available: 12, occupied: 2500, capacity: 6000 },
    roads: { closed: 25, congested: 60, safe: 40 },
    population: { affected: 35000, evacuated: 8000, atRisk: 100000 },
    map: DEFAULT_MAP
  },
  [FloodStage.SHELTER_ACTIVATED]: {
    stageEnum: FloodStage.SHELTER_ACTIVATED,
    name: 'Shelter Activated',
    description: 'Additional emergency shelters opened.',
    durationMs: 0,
    weather: { temperature: 23, rainfall: 60, humidity: 95, windSpeed: 30, condition: 'Heavy Rain' },
    threat: { riskLevel: 'CRITICAL', riskScore: 92, confidence: 95 },
    ai: { title: 'Shelter Capacity Nearing', summary: 'Primary shelters reaching 80% capacity.', recommendation: 'Activate secondary municipal shelters.', reasoning: ['Displaced population surging', 'Current capacity insufficient'], confidence: 98 },
    incidentFeed: [{ id: 'inc-6', title: 'New Shelters Opened', description: '3 schools repurposed as shelters.', severity: 'medium', timestampOffset: 1, location: { lat: 19.085, lng: 72.895 } }],
    resources: { rescueTeams: { deployed: 15, available: 0 }, ambulances: { deployed: 38, available: 4 }, fireUnits: { deployed: 28, available: 3 }, police: { deployed: 95, available: 15 } },
    shelters: { available: 18, occupied: 5200, capacity: 9000 },
    roads: { closed: 28, congested: 55, safe: 42 },
    population: { affected: 50000, evacuated: 12000, atRisk: 120000 },
    map: DEFAULT_MAP
  },
  [FloodStage.RESCUE_DEPLOYMENT]: {
    stageEnum: FloodStage.RESCUE_DEPLOYMENT,
    name: 'Rescue Deployment',
    description: 'Active water rescue operations underway.',
    durationMs: 0,
    weather: { temperature: 24, rainfall: 30, humidity: 90, windSpeed: 20, condition: 'Moderate Rain' },
    threat: { riskLevel: 'HIGH', riskScore: 85, confidence: 96 },
    ai: { title: 'Rescue Operations', summary: 'Stranded citizens require airlift and boat rescue.', recommendation: 'Deploy NDRF boat teams to Sector 5.', reasoning: ['Water depth exceeds 5 feet', '100+ distress calls logged'], confidence: 99 },
    incidentFeed: [{ id: 'inc-7', title: 'Boat Rescue Initiated', description: 'NDRF deployed for stranded citizens.', severity: 'critical', timestampOffset: 0, location: { lat: 19.070, lng: 72.880 } }],
    resources: { rescueTeams: { deployed: 15, available: 0 }, ambulances: { deployed: 40, available: 2 }, fireUnits: { deployed: 30, available: 1 }, police: { deployed: 100, available: 10 } },
    shelters: { available: 20, occupied: 7800, capacity: 10000 },
    roads: { closed: 30, congested: 45, safe: 50 },
    population: { affected: 65000, evacuated: 18000, atRisk: 120000 },
    map: DEFAULT_MAP
  },
  [FloodStage.SITUATION_STABILIZED]: {
    stageEnum: FloodStage.SITUATION_STABILIZED,
    name: 'Situation Stabilized',
    description: 'Rain stops, water levels plateau.',
    durationMs: 0,
    weather: { temperature: 25, rainfall: 5, humidity: 85, windSpeed: 15, condition: 'Drizzle' },
    threat: { riskLevel: 'MODERATE', riskScore: 50, confidence: 90 },
    ai: { title: 'Threat Downgraded', summary: 'Weather system passing, water levels stable.', recommendation: 'Begin damage assessment protocols.', reasoning: ['No significant rainfall in 2 hours', 'River levels dropping'], confidence: 95 },
    incidentFeed: [{ id: 'inc-8', title: 'Water Receding', description: 'Water levels dropping in central zones.', severity: 'low', timestampOffset: 5, location: { lat: 19.075, lng: 72.875 } }],
    resources: { rescueTeams: { deployed: 10, available: 5 }, ambulances: { deployed: 20, available: 22 }, fireUnits: { deployed: 15, available: 16 }, police: { deployed: 60, available: 50 } },
    shelters: { available: 20, occupied: 8500, capacity: 10000 },
    roads: { closed: 15, congested: 30, safe: 80 },
    population: { affected: 65000, evacuated: 21000, atRisk: 50000 },
    map: DEFAULT_MAP
  },
  [FloodStage.RECOVERY]: {
    stageEnum: FloodStage.RECOVERY,
    name: 'Recovery',
    description: 'Cleanup and infrastructure repair begins.',
    durationMs: 0,
    weather: { temperature: 26, rainfall: 0, humidity: 75, windSpeed: 10, condition: 'Cloudy' },
    threat: { riskLevel: 'LOW', riskScore: 20, confidence: 95 },
    ai: { title: 'Initiate Recovery', summary: 'Focus shifting to sanitation and power restoration.', recommendation: 'Dispatch utility crews.', reasoning: ['Flood waters largely cleared', 'Disease risk emerging'], confidence: 90 },
    incidentFeed: [{ id: 'inc-9', title: 'Power Restoration', description: 'Grid coming back online in Sector 3.', severity: 'low', timestampOffset: 2, location: { lat: 19.065, lng: 72.865 } }],
    resources: { rescueTeams: { deployed: 2, available: 13 }, ambulances: { deployed: 10, available: 32 }, fireUnits: { deployed: 5, available: 26 }, police: { deployed: 40, available: 70 } },
    shelters: { available: 20, occupied: 6000, capacity: 10000 },
    roads: { closed: 5, congested: 20, safe: 100 },
    population: { affected: 65000, evacuated: 15000, atRisk: 10000 },
    map: DEFAULT_MAP
  },
  [FloodStage.COMPLETED]: {
    stageEnum: FloodStage.COMPLETED,
    name: 'Completed',
    description: 'Simulation completed.',
    durationMs: 0,
    weather: { temperature: 28, rainfall: 0, humidity: 65, windSpeed: 5, condition: 'Clear' },
    threat: { riskLevel: 'LOW', riskScore: 5, confidence: 99 },
    ai: { title: 'Operations Concluded', summary: 'Emergency response deactivated.', recommendation: 'Generate final incident report.', reasoning: ['All critical metrics nominal'], confidence: 99 },
    incidentFeed: [],
    resources: { rescueTeams: { deployed: 0, available: 15 }, ambulances: { deployed: 0, available: 42 }, fireUnits: { deployed: 0, available: 31 }, police: { deployed: 10, available: 100 } },
    shelters: { available: 20, occupied: 1000, capacity: 10000 },
    roads: { closed: 0, congested: 10, safe: 115 },
    population: { affected: 65000, evacuated: 0, atRisk: 0 },
    map: DEFAULT_MAP
  }
};
