export enum FloodStage {
  NORMAL = 'NORMAL',
  HEAVY_RAIN = 'HEAVY_RAIN',
  CITIZEN_REPORTS = 'CITIZEN_REPORTS',
  WATER_LEVEL_RISING = 'WATER_LEVEL_RISING',
  FLOOD_WARNING = 'FLOOD_WARNING',
  ROAD_CLOSURE = 'ROAD_CLOSURE',
  SHELTER_ACTIVATED = 'SHELTER_ACTIVATED',
  RESCUE_DEPLOYMENT = 'RESCUE_DEPLOYMENT',
  SITUATION_STABILIZED = 'SITUATION_STABILIZED',
  RECOVERY = 'RECOVERY',
  COMPLETED = 'COMPLETED'
}

export const FLOOD_STAGE_SEQUENCE = [
  FloodStage.NORMAL,
  FloodStage.HEAVY_RAIN,
  FloodStage.CITIZEN_REPORTS,
  FloodStage.WATER_LEVEL_RISING,
  FloodStage.FLOOD_WARNING,
  FloodStage.ROAD_CLOSURE,
  FloodStage.SHELTER_ACTIVATED,
  FloodStage.RESCUE_DEPLOYMENT,
  FloodStage.SITUATION_STABILIZED,
  FloodStage.RECOVERY,
  FloodStage.COMPLETED
];
